export enum EJwtConfigKey {
  JWT_SECRET = 'JWT_SECRET',
  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
  JWT_RESET_PASSWORD_TOKEN_SECRET = 'JWT_RESET_PASSWORD_TOKEN_SECRET',
  JWT_RESET_PASSWORD_TOKEN_EXPIRATION_TIME = 'JWT_RESET_PASSWORD_TOKEN_EXPIRATION_TIME',
  JWT_VERIFY_ACCOUNT_TOKEN_SECRET = 'JWT_VERIFY_ACCOUNT_TOKEN_SECRET',
  JWT_VERIFY_ACCOUNT_TOKEN_EXPIRATION_TIME = 'JWT_VERIFY_ACCOUNT_TOKEN_EXPIRATION_TIME'
}

export enum ETokenType {
  ACCESS = 0,
  REFRESH = 1,
  RESET_PASSWORD = 2,
  VERIFY_ACCOUNT = 3
}
